@extends('layouts.master')
@section('title', __('Submit pending collection'))
@section('content')
@php($collectionLines = $receivables ?? collect([$receivable]))
@php($currency = $collectionLines->first()->currency)
@php($hasAvailable = $collectionLines->contains(fn ($line) => \App\Support\CentralFinanceDecimal::compare((string) ($line->available_to_collect ?? '0'), '0') > 0))
<div class="container-fluid py-3"><div class="card"><div class="card-body"><p class="text-uppercase text-muted mb-1">{{ __('School Finance') }} · {{ $school->name }}</p><h3>{{ __('Submit pending collection') }}</h3><p>{{ $profile->student_name }} · {{ __('One parent collection with explicit receivable allocations') }}</p>
<p class="text-muted">{{ __('This does not create a Payment, Receipt, Ledger entry, or Fund Account balance change until Head Finance confirms it.') }}</p>
<div class="table-responsive mb-3"><table class="table table-sm"><thead><tr><th>{{ __('Receivable') }}</th><th>{{ __('Gross') }}</th><th>{{ __('Promotion') }}</th><th>{{ __('Net due') }}</th><th>{{ __('Confirmed paid') }}</th><th>{{ __('Pending') }}</th><th>{{ __('Available') }}</th><th>{{ __('Collect now') }}</th></tr></thead><tbody>@foreach($collectionLines as $line)@php($gross = \App\Support\CentralFinanceDecimal::normalize((string) ($line->source_amount_due ?? $line->amount_due)))@php($promotion = \App\Support\CentralFinanceDecimal::max(\App\Support\CentralFinanceDecimal::subtract($gross, (string) $line->amount_due), '0'))@php($pendingConfirmation = \App\Support\CentralFinanceDecimal::max((string) ($line->pending_confirmation_amount ?? '0'), '0'))@php($available = \App\Support\CentralFinanceDecimal::max(\App\Support\CentralFinanceDecimal::subtract(\App\Support\CentralFinanceDecimal::subtract((string) $line->amount_due, (string) $line->amount_paid), $pendingConfirmation), '0'))<tr><td>{{ $line->description }}</td><td>{{ number_format((float) $gross,2) }}</td><td>{{ number_format((float) $promotion,2) }}</td><td>{{ number_format((float) $line->amount_due,2) }}</td><td>{{ number_format((float) $line->amount_paid,2) }}</td><td class="text-warning">{{ number_format((float) $pendingConfirmation,2) }}</td><td class="text-info">{{ number_format((float) $available,2) }}</td><td><input class="form-control form-control-sm allocation-amount" name="allocations[{{ $line->id }}]" type="number" min="0.0001" step="0.0001" max="{{ $available }}" value="{{ \App\Support\CentralFinanceDecimal::compare($available, '0') > 0 ? $available : '' }}" required @disabled(\App\Support\CentralFinanceDecimal::compare($available, '0') <= 0) form="pending-collection-form"></td></tr>@endforeach</tbody><tfoot><tr><th colspan="7" class="text-right">{{ __('Collection total') }}</th><th><span id="allocation-total">0.0000</span> {{ $currency }}</th></tr></tfoot></table></div>
@if(!$hasAvailable)<div class="alert alert-warning">{{ __('All selected receivables are fully reserved by pending Finance confirmation.') }}</div>@endif
<form id="pending-collection-form" method="POST" action="{{ route('central-finance.pending-collections.submit-multiple', $profile->id) }}">@csrf<input type="hidden" name="pending_attempt_uuid" value="{{ $attemptUuid }}"><div class="form-row"><div class="col-md-4 form-group"><label>{{ __('Payment method') }}</label><select class="form-control" id="payment-method" name="payment_method" required @disabled(!$hasAvailable)><option value="Cash">{{ __('Cash') }}</option><option value="Bank Transfer">{{ __('Bank Transfer') }}</option></select></div><div class="col-md-4 form-group"><label>{{ __('Reference') }}</label><input class="form-control" name="payment_reference" maxlength="100" @disabled(!$hasAvailable)><small class="form-text text-muted">{{ __('A reference already used or reserved in this School is rejected before submission.') }}</small></div></div><div class="form-row"><div class="col-md-6 form-group" id="bank-account-field"><label>{{ __('Destination Bank Account') }}</label><select class="form-control" name="intended_fund_account_id" @disabled(!$hasAvailable)><option value="">{{ __('Select allocated Bank Fund Account') }}</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->account_name }} · {{ $account->currency }}</option>@endforeach</select><small class="form-text text-muted">{{ __('The account is only declared here. Head Finance revalidates it before official posting.') }}</small></div><div class="col-md-6 form-group"><label>{{ __('Note') }}</label><input class="form-control" name="note" maxlength="2000" @disabled(!$hasAvailable)></div></div><button class="btn cf-primary-action" @disabled(!$hasAvailable)>{{ __('Submit pending collection') }}</button></form></div></div></div>
@endsection

@section('js')
<script>document.addEventListener('DOMContentLoaded',()=>{const method=document.getElementById('payment-method'),field=document.getElementById('bank-account-field'),select=field.querySelector('select'),inputs=[...document.querySelectorAll('.allocation-amount')],total=document.getElementById('allocation-total');const sync=()=>{const bank=method.value==='Bank Transfer';field.hidden=!bank;select.required=bank;if(!bank)select.value='';};const sum=()=>{total.textContent=inputs.reduce((value,input)=>value+(Number.parseFloat(input.value)||0),0).toFixed(4);};method.addEventListener('change',sync);inputs.forEach(input=>input.addEventListener('input',sum));sync();sum();});</script>
@endsection
