<?php
namespace Tests\Feature;
use App\Models\CentralFinanceFundAccount; use App\Models\CentralFinancePayment; use App\Models\CentralFinanceReceivable; use App\Models\CentralFinanceStudentProfile; use App\Models\CentralFinanceUser; use App\Models\School; use App\Services\CentralFinanceFundAccountBalanceService; use App\Services\CentralFinancePaymentService; use App\Services\CentralFinanceReceivableSyncService; use Carbon\CarbonImmutable; use Illuminate\Auth\Access\AuthorizationException; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Config; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema; use Illuminate\Support\Str; use InvalidArgumentException; use Tests\TestCase;

class CentralFinanceReceivablePaymentTest extends TestCase {
 private string $central; private string $a; private string $b; private CentralFinanceUser $head; private CentralFinanceUser $accountant; private CentralFinanceFundAccount $hq; private CentralFinanceFundAccount $zix; private CentralFinanceStudentProfile $zixProfile; private CentralFinanceStudentProfile $timeProfile;
 protected function setUp(): void { parent::setUp(); $this->central=tempnam(sys_get_temp_dir(),'cf_recv_c_'); $this->a=tempnam(sys_get_temp_dir(),'cf_recv_a_'); $this->b=tempnam(sys_get_temp_dir(),'cf_recv_b_'); Config::set('database.connections.mysql',['driver'=>'sqlite','database'=>$this->central,'prefix'=>'','foreign_key_constraints'=>true]); Config::set('database.connections.school',['driver'=>'sqlite','database'=>$this->a,'prefix'=>'','foreign_key_constraints'=>true]); DB::purge('mysql'); DB::purge('school'); DB::setDefaultConnection('mysql');
  Schema::connection('mysql')->create('schools',fn(Blueprint $t)=>[$t->id(),$t->string('name'),$t->string('code')->nullable(),$t->string('database_name')->nullable(),$t->softDeletes(),$t->timestamps()]); Schema::connection('mysql')->create('users',fn(Blueprint $t)=>[$t->id(),$t->string('first_name')->nullable(),$t->string('last_name')->nullable(),$t->softDeletes(),$t->timestamps()]);
  (require database_path('migrations/2026_08_20_000003_create_central_finance_student_sync_tables.php'))->up(); (require database_path('migrations/2026_08_20_000004_add_academic_and_guardian_references_to_central_finance_student_profiles.php'))->up(); (require database_path('migrations/2026_08_20_000005_create_central_finance_fund_accounts_and_ledger.php'))->up(); (require database_path('migrations/2026_08_21_000001_create_central_finance_receivables_payments_and_receipts.php'))->up(); (require database_path('migrations/2026_08_21_000005_create_central_finance_school_cutovers.php'))->up(); (require database_path('migrations/2026_08_25_000001_create_central_finance_receivable_sync_events.php'))->up(); (require database_path('migrations/2026_08_25_000003_create_central_finance_receivable_adjustments.php'))->up(); (require database_path('migrations/2026_08_25_000005_add_fresh_start_receivable_cutoff.php'))->up();
  DB::connection('mysql')->table('schools')->insert([['id'=>1,'name'=>'Zixuan QA','code'=>'ZIX','database_name'=>$this->a,'created_at'=>now(),'updated_at'=>now()],['id'=>2,'name'=>'Timecity QA','code'=>'TIM','database_name'=>$this->b,'created_at'=>now(),'updated_at'=>now()]]); DB::connection('mysql')->table('users')->insert([['id'=>100,'first_name'=>'Head','last_name'=>'Finance','created_at'=>now(),'updated_at'=>now()],['id'=>200,'first_name'=>'School','last_name'=>'Accountant','created_at'=>now(),'updated_at'=>now()]]); DB::connection('mysql')->table('central_finance_school_cutovers')->insert([['school_id'=>1,'status'=>'central','receivable_sync_effective_at'=>'2026-08-01 00:00:00','cutover_at'=>now(),'created_at'=>now(),'updated_at'=>now()],['school_id'=>2,'status'=>'central','receivable_sync_effective_at'=>'2026-08-01 00:00:00','cutover_at'=>now(),'created_at'=>now(),'updated_at'=>now()]]); $this->head=CentralFinanceUser::on('mysql')->findOrFail(100); $this->accountant=CentralFinanceUser::on('mysql')->findOrFail(200);
  $this->tenant($this->a,'Zixuan Tuition',1000); $this->tenant($this->b,'Timecity Tuition',2000);
  $this->zixProfile=$this->profile(1,'11111111-1111-4111-8111-111111111111'); $this->timeProfile=$this->profile(2,'22222222-2222-4222-8222-222222222222'); $this->hq=$this->account('CF-HQ','HQ Bank','hq',null); $this->zix=$this->account('CF-ZIX','Zixuan Cash','school',1); foreach([$this->hq,$this->zix] as $account) $this->grant($this->head,$account); $this->grant($this->accountant,$this->zix); $this->schoolGrant($this->head,1); $this->schoolGrant($this->head,2); $this->schoolGrant($this->accountant,1);
 }
 protected function tearDown(): void { DB::purge('mysql');DB::purge('school');foreach([$this->central,$this->a,$this->b] as $f)@unlink($f);parent::tearDown(); }
 public function test_tenant_fee_assignments_create_idempotent_school_scoped_receivables_without_tenant_writes(): void { $before=$this->tenantHash(); $sync=app(CentralFinanceReceivableSyncService::class); $sync->syncProfile($this->zixProfile);$sync->syncProfile($this->timeProfile);$sync->syncProfile($this->zixProfile); $this->assertSame(2,CentralFinanceReceivable::on('mysql')->count()); $this->assertSame($before,$this->tenantHash()); $this->assertSame(1000.0,(float)CentralFinanceReceivable::on('mysql')->where('school_id',1)->firstOrFail()->amount_due); }
 public function test_legacy_tenant_fee_assignment_without_currency_column_defaults_to_mmk(): void { $previous=config('database.connections.school.database');try{Config::set('database.connections.school.database',$this->a);DB::purge('school');Schema::connection('school')->table('fees_class_types',fn(Blueprint $table)=>$table->dropColumn('fee_currency'));}finally{DB::purge('school');Config::set('database.connections.school.database',$previous);} $receivable=$this->receivable($this->zixProfile);$this->assertSame('MMK',$receivable->currency); }
 public function test_fresh_start_cutoff_excludes_pre_cutoff_assignments_without_cancelling_them_or_writing_tenant_finance(): void { DB::connection('mysql')->table('central_finance_school_cutovers')->where('school_id',1)->update(['receivable_sync_effective_at'=>'2026-08-25 00:00:00']); $previous=config('database.connections.school.database'); try { Config::set('database.connections.school.database',$this->a); DB::purge('school'); DB::connection('school')->table('fees_class_types')->where('id',1)->update(['created_at'=>'2026-08-20 00:00:00','updated_at'=>'2026-08-26 00:00:00']); DB::connection('school')->table('fees')->insert(['id'=>2,'name'=>'Post-cutoff tuition','due_date'=>'2026-09-02','created_at'=>'2026-08-26 00:00:00','updated_at'=>'2026-08-26 00:00:00']); DB::connection('school')->table('fees_class_types')->insert(['id'=>2,'fees_id'=>2,'class_id'=>1,'amount'=>333,'optional'=>0,'fee_currency'=>'MMK','created_at'=>'2026-08-26 00:00:00','updated_at'=>'2026-08-26 00:00:00']); } finally { DB::purge('school'); Config::set('database.connections.school.database',$previous); } $before=$this->tenantHash(); $sync=app(CentralFinanceReceivableSyncService::class); $sync->syncProfile($this->zixProfile); $rows=CentralFinanceReceivable::on('mysql')->where('school_id',1)->get(); $this->assertCount(1,$rows); $this->assertSame('2',(string)$rows->first()->source_id); $this->assertSame('2026-08-26 00:00:00',$rows->first()->source_created_at->format('Y-m-d H:i:s')); $report=$sync->reconcileSchool(School::on('mysql')->findOrFail(1)); $this->assertSame(1,$report['source_count']); $this->assertSame(1,$report['central_count']); $this->assertSame([],$report['missing_in_central']); $this->assertSame($before,$this->tenantHash()); }
 public function test_partial_and_full_collection_create_one_payment_receipt_and_ledger_per_idempotency_key(): void { $r=$this->receivable($this->zixProfile);$pay=app(CentralFinancePaymentService::class);$at=CarbonImmutable::parse('2026-08-21 09:00','Asia/Yangon'); $first=$pay->collect($this->head,$r->id,$this->zix,400,'Cash',$at,'ZIX-PAY-1','ZIX-REF-1');$retry=$pay->collect($this->head,$r->id,$this->zix,400,'Cash',$at,'ZIX-PAY-1','ZIX-REF-1'); $this->assertSame($first['payment']->id,$retry['payment']->id);$r->refresh();$this->assertSame(CentralFinanceReceivable::PARTIAL,$r->status);$this->assertSame(400.0,(float)$r->amount_paid);$pay->collect($this->head,$r->id,$this->zix,600,'Cash',$at,'ZIX-PAY-2','ZIX-REF-2');$r->refresh();$this->assertSame(CentralFinanceReceivable::PAID,$r->status);$this->assertSame(1000.0,app(CentralFinanceFundAccountBalanceService::class)->currentBalance($this->zix));$this->assertSame(2,CentralFinancePayment::on('mysql')->count());$this->assertSame(2,DB::connection('mysql')->table('central_finance_receipts')->count());$this->assertSame(2,DB::connection('mysql')->table('central_finance_ledger_entries')->count()); }
 public function test_hq_account_can_receive_timecity_tuition_but_income_remains_timecity_attributed(): void { $r=$this->receivable($this->timeProfile);app(CentralFinancePaymentService::class)->collect($this->head,$r->id,$this->hq,2000,'Bank',$this->at(),'TIM-PAY-1','TIM-REF-1');$this->assertSame(2000.0,app(CentralFinanceFundAccountBalanceService::class)->currentBalance($this->hq));$total=app(CentralFinanceFundAccountBalanceService::class)->totalsForSchool(2);$this->assertSame(2000.0,$total['money_in']);$this->assertSame(2000.0,$total['operating_income']);$this->assertSame(0.0,$total['operating_expense']); }
 public function test_unscoped_accountant_and_duplicate_reference_are_rejected_without_extra_finance_records(): void { $r=$this->receivable($this->timeProfile);$pay=app(CentralFinancePaymentService::class);try{$pay->collect($this->accountant,$r->id,$this->hq,10,'Cash',$this->at(),'BAD-1','BAD-REF');$this->fail();}catch(AuthorizationException){$this->assertSame(0,CentralFinancePayment::on('mysql')->count());}$r=$this->receivable($this->zixProfile);$pay->collect($this->head,$r->id,$this->zix,10,'Cash',$this->at(),'Z-1','SAME-REF');try{$pay->collect($this->head,$r->id,$this->zix,10,'Cash',$this->at(),'Z-2','SAME-REF');$this->fail();}catch(InvalidArgumentException){$this->assertSame(1,CentralFinancePayment::on('mysql')->count());}}
 public function test_cross_school_or_inactive_fund_account_is_rejected_without_payment_or_ledger(): void { $r=$this->receivable($this->zixProfile);$time=$this->account('CF-TIM','Timecity Cash','school',2);$this->grant($this->head,$time);$paymentsBefore=CentralFinancePayment::on('mysql')->count();$ledgerBefore=DB::connection('mysql')->table('central_finance_ledger_entries')->count();try{app(CentralFinancePaymentService::class)->collect($this->head,$r->id,$time,10,'Cash',$this->at(),'Z-TIM','Z-TIM');$this->fail();}catch(InvalidArgumentException){$this->assertSame($paymentsBefore,CentralFinancePayment::on('mysql')->count());$this->assertSame($ledgerBefore,DB::connection('mysql')->table('central_finance_ledger_entries')->count());}$this->zix->update(['is_active'=>false]);try{app(CentralFinancePaymentService::class)->collect($this->head,$r->id,$this->zix,10,'Cash',$this->at(),'Z-INACTIVE','Z-INACTIVE');$this->fail();}catch(\Illuminate\Database\Eloquent\ModelNotFoundException){$this->assertSame($paymentsBefore,CentralFinancePayment::on('mysql')->count());$this->assertSame($ledgerBefore,DB::connection('mysql')->table('central_finance_ledger_entries')->count());}}
 public function test_receivable_schema_is_additive_and_reversible_without_tenant_finance_changes(): void { $migration=require database_path('migrations/2026_08_21_000001_create_central_finance_receivables_payments_and_receipts.php');$migration->down();foreach(['central_finance_receipts','central_finance_payments','central_finance_receivables','central_finance_user_school_scopes'] as $table)$this->assertFalse(Schema::connection('mysql')->hasTable($table));$this->assertTrue(Schema::connection('school')->hasTable('fees'));$this->assertTrue(Schema::connection('school')->hasTable('fees_class_types'));}
 private function receivable(CentralFinanceStudentProfile $p): CentralFinanceReceivable { app(CentralFinanceReceivableSyncService::class)->syncProfile($p);return CentralFinanceReceivable::on('mysql')->where('student_profile_id',$p->id)->firstOrFail(); }
 private function at():CarbonImmutable{return CarbonImmutable::parse('2026-08-21 10:00','Asia/Yangon');}
 private function profile(int $school,string $uuid):CentralFinanceStudentProfile{return CentralFinanceStudentProfile::on('mysql')->create(['school_id'=>$school,'tenant_student_id'=>$school,'source_uuid'=>$uuid,'class_id'=>1,'class_section_id'=>1,'student_name'=>'Student '.$school,'enrollment_status'=>'active','source_updated_at'=>now(),'last_synced_at'=>now()]);}
 private function account(string $code,string $name,string $type,?int $school):CentralFinanceFundAccount{return CentralFinanceFundAccount::on('mysql')->create(['account_uuid'=>(string)Str::uuid(),'group_id'=>1,'school_id'=>$school,'owner_type'=>$type,'account_code'=>$code,'account_name'=>$name,'currency'=>'MMK','opening_balance'=>0,'is_active'=>true]);}
 private function grant(CentralFinanceUser $u,CentralFinanceFundAccount $a):void{DB::connection('mysql')->table('central_finance_fund_account_users')->insert(['fund_account_id'=>$a->id,'user_id'=>$u->id,'can_view'=>1,'can_operate'=>1,'created_at'=>now(),'updated_at'=>now()]);}
 private function schoolGrant(CentralFinanceUser $u,int $s):void{DB::connection('mysql')->table('central_finance_user_school_scopes')->insert(['user_id'=>$u->id,'school_id'=>$s,'can_view'=>1,'can_operate'=>1,'created_at'=>now(),'updated_at'=>now()]);}
 private function tenant(string $db,string $name,float $amount):void{Config::set('database.connections.school.database',$db);DB::purge('school');Schema::connection('school')->create('fees',fn(Blueprint $t)=>[$t->id(),$t->string('name'),$t->date('due_date')->nullable(),$t->timestamps()]);Schema::connection('school')->create('fees_class_types',fn(Blueprint $t)=>[$t->id(),$t->unsignedBigInteger('fees_id'),$t->unsignedBigInteger('class_id'),$t->decimal('amount',20,4),$t->boolean('optional')->default(false),$t->string('fee_currency',3)->nullable(),$t->timestamps()]);DB::connection('school')->table('fees')->insert(['id'=>1,'name'=>$name,'due_date'=>'2026-09-01','created_at'=>now(),'updated_at'=>now()]);DB::connection('school')->table('fees_class_types')->insert(['id'=>1,'fees_id'=>1,'class_id'=>1,'amount'=>$amount,'optional'=>0,'fee_currency'=>'MMK','created_at'=>now(),'updated_at'=>now()]);}
 private function tenantHash():string{$rows=[];foreach([$this->a,$this->b]as$db){Config::set('database.connections.school.database',$db);DB::purge('school');$rows[]=DB::connection('school')->table('fees')->orderBy('id')->get()->map(fn($r)=>(array)$r)->all();$rows[]=DB::connection('school')->table('fees_class_types')->orderBy('id')->get()->map(fn($r)=>(array)$r)->all();}return hash('sha256',serialize($rows));}
}
