<?php
namespace Tests\Feature;
use App\Http\Controllers\FinanceStaffController; use App\Services\FinanceAccountAccessService;
use App\Models\BankAccount; use App\Models\User; use Illuminate\Foundation\Testing\DatabaseTransactions; use Illuminate\Http\Request; use Illuminate\Support\Facades\Auth; use Illuminate\Support\Facades\DB; use Tests\TestCase;
class FinanceStaffControllerTest extends TestCase { use DatabaseTransactions; protected $connectionsToTransact=['school'];
 private function user($role){$u=User::create(['first_name'=>'QA','last_name'=>$role,'email'=>uniqid().'@qa.test','password'=>bcrypt('x'),'school_id'=>1,'status'=>1]);DB::table('roles')->updateOrInsert(['name'=>$role,'school_id'=>1],['guard_name'=>'web','created_at'=>now(),'updated_at'=>now()]);$r=DB::table('roles')->where('name',$role)->where('school_id',1)->value('id');DB::table('model_has_roles')->insert(['role_id'=>$r,'model_id'=>$u->id,'model_type'=>User::class]);return $u;}
 public function test_school_admin_controls_roles_and_removing_cashier_detaches_accounts():void{$a=$this->user('School Admin');$c=$this->user('Cashier');$b=BankAccount::create(['school_id'=>1,'account_name'=>'QA','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);$c->authorized_bank_accounts()->attach($b);Auth::login($a);app(FinanceStaffController::class)->role(new Request(['role'=>'Cashier','action'=>'remove']),$c);$this->assertFalse($c->fresh()->hasRole('Cashier'));$this->assertCount(0,$c->fresh()->authorized_bank_accounts);}
 public function test_head_finance_cannot_grant_roles_but_can_assign_active_cashier_account():void{$h=$this->user('Head Finance');$c=$this->user('Cashier');$b=BankAccount::create(['school_id'=>1,'account_name'=>'QA','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);Auth::login($h);app(FinanceStaffController::class)->accounts(new Request(['account_ids'=>[$b->id]]),$c,app(FinanceAccountAccessService::class));$this->assertSame([$b->id],$c->authorized_bank_accounts()->pluck('bank_accounts.id')->all());$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);app(FinanceStaffController::class)->role(new Request(['role'=>'Cashier','action'=>'assign']),$c);}
 public function test_cashier_and_forged_or_inactive_assignments_are_rejected():void{$cash=$this->user('Cashier');$target=$this->user('Cashier');$inactive=BankAccount::create(['school_id'=>1,'account_name'=>'Inactive','account_type'=>'cash','currency'=>'MMK','is_active'=>0]);Auth::login($cash);$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);app(FinanceStaffController::class)->accounts(new Request(['account_ids'=>[$inactive->id]]),$target,app(FinanceAccountAccessService::class));}
}
