<?php
namespace Tests\Feature;
use App\Http\Controllers\FinanceStaffController; use App\Services\FinanceAccountAccessService; use App\Services\TenantPasswordBroker;
use App\Models\BankAccount; use App\Models\User; use App\Models\Role; use Illuminate\Foundation\Testing\DatabaseTransactions; use Illuminate\Http\Request; use Illuminate\Support\Facades\Auth; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Password; use Spatie\Permission\Models\Permission; use Tests\TestCase;
class FinanceStaffControllerTest extends TestCase { protected bool $tenantDbAsDefault = true; use DatabaseTransactions; protected $connectionsToTransact=['school'];
 private function user($role){$u=User::create(['first_name'=>'QA','last_name'=>$role,'email'=>uniqid().'@qa.test','password'=>bcrypt('x'),'school_id'=>1,'status'=>1]);DB::table('roles')->updateOrInsert(['name'=>$role,'school_id'=>1],['guard_name'=>'web','created_at'=>now(),'updated_at'=>now()]);$r=DB::table('roles')->where('name',$role)->where('school_id',1)->value('id');DB::table('model_has_roles')->insert(['role_id'=>$r,'model_id'=>$u->id,'model_type'=>User::class]);if(in_array($role,['School Admin','Head Finance'],true)){Permission::findOrCreate('finance-staff-manage','web');Role::withoutGlobalScope('school')->find($r)->givePermissionTo('finance-staff-manage');}return $u;}
 public function test_school_admin_cannot_control_finance_roles_or_account_assignments():void{$a=$this->user('School Admin');$c=$this->user('Cashier');$b=BankAccount::create(['school_id'=>1,'account_name'=>'QA','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);$c->authorized_bank_accounts()->attach($b);Auth::login($a);try{app(FinanceStaffController::class)->role(new Request(['role'=>'Cashier','action'=>'remove']),$c);$this->fail('School Admin must be denied.');}catch(\Symfony\Component\HttpKernel\Exception\HttpException $exception){$this->assertSame(403,$exception->getStatusCode());}$this->assertTrue($c->fresh()->hasRole('Cashier'));$this->assertCount(1,$c->fresh()->authorized_bank_accounts);}
 public function test_head_finance_cannot_grant_roles_but_can_assign_active_cashier_account():void{$h=$this->user('Head Finance');$c=$this->user('Cashier');$b=BankAccount::create(['school_id'=>1,'account_name'=>'QA','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);Auth::login($h);app(FinanceStaffController::class)->accounts(new Request(['account_ids'=>[$b->id]]),$c,app(FinanceAccountAccessService::class));$this->assertSame([$b->id],$c->authorized_bank_accounts()->pluck('bank_accounts.id')->all());$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);app(FinanceStaffController::class)->role(new Request(['role'=>'Cashier','action'=>'assign']),$c);}
 public function test_account_assignment_replaces_the_full_set_and_missing_ids_clear_the_last_assignment():void{
  $head=$this->user('Head Finance');$cashier=$this->user('Cashier');$unrelated=$this->user('Cashier');
  $first=BankAccount::create(['school_id'=>1,'account_name'=>'First','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);
  $second=BankAccount::create(['school_id'=>1,'account_name'=>'Second','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);
  $cashier->authorized_bank_accounts()->sync([$first->id,$second->id]);$unrelated->authorized_bank_accounts()->sync([$second->id]);Auth::login($head);
  $controller=app(FinanceStaffController::class);$access=app(FinanceAccountAccessService::class);
  $controller->accounts(new Request(['account_ids'=>[$first->id]]),$cashier,$access);
  $this->assertSame([$first->id],$cashier->fresh()->authorized_bank_accounts()->pluck('bank_accounts.id')->all());
  $controller->accounts(new Request([]),$cashier,$access);
  $this->assertCount(0,$cashier->fresh()->authorized_bank_accounts);
  $controller->accounts(new Request([]),$cashier,$access);
  $this->assertCount(0,$cashier->fresh()->authorized_bank_accounts);
  $this->assertSame([$second->id],$unrelated->fresh()->authorized_bank_accounts()->pluck('bank_accounts.id')->all());
 }
 public function test_account_assignment_rejects_deleted_and_cross_school_accounts_without_changing_pivots():void{
  $head=$this->user('Head Finance');$cashier=$this->user('Cashier');$active=BankAccount::create(['school_id'=>1,'account_name'=>'Active','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);$deleted=BankAccount::create(['school_id'=>1,'account_name'=>'Deleted','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);$deleted->delete();$foreign=BankAccount::create(['school_id'=>2,'account_name'=>'Foreign','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);$cashier->authorized_bank_accounts()->sync([$active->id]);Auth::login($head);$controller=app(FinanceStaffController::class);$access=app(FinanceAccountAccessService::class);
  foreach([$deleted->id,$foreign->id] as $invalid){try{$controller->accounts(new Request(['account_ids'=>[$invalid]]),$cashier,$access);$this->fail('Invalid account assignment must be rejected.');}catch(\Symfony\Component\HttpKernel\Exception\HttpException $exception){$this->assertSame(422,$exception->getStatusCode());}}
  $this->assertSame([$active->id],$cashier->fresh()->authorized_bank_accounts()->pluck('bank_accounts.id')->all());
 }
 public function test_cashier_and_forged_or_inactive_assignments_are_rejected():void{$cash=$this->user('Cashier');$target=$this->user('Cashier');$inactive=BankAccount::create(['school_id'=>1,'account_name'=>'Inactive','account_type'=>'cash','currency'=>'MMK','is_active'=>0]);Auth::login($cash);$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);app(FinanceStaffController::class)->accounts(new Request(['account_ids'=>[$inactive->id]]),$target,app(FinanceAccountAccessService::class));}
 public function test_head_finance_creates_only_an_accountant_with_optional_active_current_school_accounts():void{$head=$this->user('Head Finance');$this->user('Cashier');$account=BankAccount::create(['school_id'=>1,'account_name'=>'Active QA','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);$email='new.accountant.'.uniqid().'@qa.test';Auth::login($head);$broker=\Mockery::mock(\Illuminate\Contracts\Auth\PasswordBroker::class);$broker->shouldReceive('sendResetLink')->once()->andReturn(Password::RESET_LINK_SENT);$tenantBroker=\Mockery::mock(TenantPasswordBroker::class);$tenantBroker->shouldReceive('broker')->once()->andReturn($broker);$this->app->instance(TenantPasswordBroker::class,$tenantBroker);$response=app(FinanceStaffController::class)->store(new Request(['first_name'=>'New','last_name'=>'Accountant','email'=>$email,'account_ids'=>[$account->id]]));$this->assertSame(200,$response->getStatusCode());$staff=User::where('email',$email)->firstOrFail();$this->assertTrue($staff->hasRole('Cashier'));$this->assertFalse(DB::table('roles')->where('name','Accountant')->exists());$this->assertSame([$account->id],$staff->authorized_bank_accounts()->pluck('bank_accounts.id')->all());$this->assertNotSame($email,$staff->password);}
 public function test_finance_staff_template_displays_accountant_for_the_internal_cashier_role():void{$template=file_get_contents(resource_path('views/finance-staff/index.blade.php'));$this->assertStringContainsString("data-role=\"Cashier\"", $template);$this->assertStringContainsString('Assign Accountant', $template);$this->assertStringContainsString('Remove Accountant', $template);$this->assertStringContainsString('Accountant Fund Accounts', $template);$this->assertStringNotContainsString('>Assign Cashier<', $template);$this->assertStringNotContainsString('>Remove Cashier<', $template);}
 public function test_accountant_onboarding_failure_leaves_no_user_role_or_account_pivots():void{$head=$this->user('Head Finance');$this->user('Cashier');$account=BankAccount::create(['school_id'=>1,'account_name'=>'Rollback QA','account_type'=>'cash','currency'=>'MMK','is_active'=>1]);$email='rollback.accountant.'.uniqid().'@qa.test';$rolesBefore=DB::table('model_has_roles')->count();$accountsBefore=DB::table('bank_account_user')->count();Auth::login($head);$broker=\Mockery::mock(\Illuminate\Contracts\Auth\PasswordBroker::class);$broker->shouldReceive('sendResetLink')->once()->andThrow(new \RuntimeException('Local mail failure'));$tenantBroker=\Mockery::mock(TenantPasswordBroker::class);$tenantBroker->shouldReceive('broker')->once()->andReturn($broker);$this->app->instance(TenantPasswordBroker::class,$tenantBroker);try{app(FinanceStaffController::class)->store(new Request(['first_name'=>'Rollback','last_name'=>'Accountant','email'=>$email,'account_ids'=>[$account->id]]));$this->fail('Expected onboarding delivery failure.');}catch(\RuntimeException $exception){$this->assertSame('Local mail failure',$exception->getMessage());}$this->assertFalse(User::where('email',$email)->exists());$this->assertSame($rolesBefore,DB::table('model_has_roles')->count());$this->assertSame($accountsBefore,DB::table('bank_account_user')->count());}
 public function test_cashier_cannot_create_accountant_and_duplicate_or_invalid_accounts_leave_no_staff_state():void{$cash=$this->user('Cashier');$this->user('Cashier');Auth::login($cash);$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);app(FinanceStaffController::class)->store(new Request(['first_name'=>'No','last_name'=>'Access','email'=>'no-access@qa.test']));}
}
