@extends('layouts.master')

@section('title', __('Central Finance'))

@section('css')
@include('central-finance.partials.foundation-styles')
@endsection

@section('content')
@php($isExpense = $type === 'expense')
@php($title = $isExpense ? __('支出记录') : __('其他收入'))
@php($indexRoute = $isExpense ? 'central-finance.expenses.index' : 'central-finance.other-income.index')
@php($updateRoute = $isExpense ? 'central-finance.expenses.update' : 'central-finance.other-income.update')
@php($voidRoute = $isExpense ? 'central-finance.expenses.void' : 'central-finance.other-income.void')
@php($ledgerSource = $isExpense ? 'central_expense' : 'central_other_income')
<div class="content-wrapper central-finance-page">
    <x-central-finance.page-header :title="$document->reference_no ?: ($isExpense ? __('Expense') : __('Other Income'))" :description="__('Posted amounts, accounts, dates, and references remain immutable. Descriptive changes and reversals are fully audited.')" :school="$school" :eyebrow="$title"><a class="btn btn-outline-secondary" href="{{ route($indexRoute) }}">{{ __('Back to list') }}</a></x-central-finance.page-header>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="row"><div class="col-lg-7 mb-3"><div class="card"><div class="card-body"><h5>{{ __('Document details') }}</h5><dl class="row mb-0"><dt class="col-sm-4">{{ __('Date') }}</dt><dd class="col-sm-8">{{ ($isExpense ? $document->expense_date : $document->income_date)?->format('Y-m-d') }}</dd><dt class="col-sm-4">{{ __('Fund Account') }}</dt><dd class="col-sm-8">#{{ $document->fund_account_id }}</dd><dt class="col-sm-4">{{ __('Category') }}</dt><dd class="col-sm-8">{{ $document->category?->name }}</dd><dt class="col-sm-4">{{ __('Amount') }}</dt><dd class="col-sm-8">{{ number_format($document->amount,2) }} {{ $document->currency }}</dd><dt class="col-sm-4">{{ __('Payment method') }}</dt><dd class="col-sm-8">{{ $document->payment_method }}</dd>@if(!$isExpense)<dt class="col-sm-4">{{ __('Payer') }}</dt><dd class="col-sm-8">{{ $document->payer ?: '—' }}</dd>@endif<dt class="col-sm-4">{{ __('Description') }}</dt><dd class="col-sm-8">{{ $document->description ?: '—' }}</dd><dt class="col-sm-4">{{ __('Status') }}</dt><dd class="col-sm-8">{{ $document->trashed() ? __('Voided / reversal recorded') : __('Active') }}</dd></dl><a class="btn btn-sm btn-outline-primary mt-3" href="{{ route('central-finance.ledger', ['source' => $ledgerSource, 'reference' => $document->reference_no]) }}">{{ __('View source Ledger') }}</a></div></div></div>
        <div class="col-lg-5 mb-3"><div class="card"><div class="card-body"><h5>{{ __('Audit timeline') }}</h5>@forelse($audits as $audit)<div class="border-left pl-3 pb-2 mb-2"><strong>{{ __($audit->action) }}</strong><div class="small text-muted">{{ $audit->created_at?->format('Y-m-d H:i') }} · {{ $audit->reason ?: __('System recorded') }}</div></div>@empty<p class="text-muted mb-0">{{ __('No audit history found.') }}</p>@endforelse</div></div></div></div>
    @if($canOperate)<div class="row"><div class="col-lg-7 mb-3"><div class="card"><div class="card-body"><h5>{{ __('Edit descriptive details') }}</h5><p class="text-muted small">{{ __('Amount, account, date, and reference remain immutable after posting. A reason is required and no Ledger row is changed.') }}</p><form method="POST" action="{{ route($updateRoute, $document->id) }}">@csrf @method('PATCH')<div class="form-group"><label>{{ __('Category') }}</label><select class="form-control" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($document->category_id === $category->id)>{{ $category->name }}</option>@endforeach</select></div>@if(!$isExpense)<div class="form-group"><label>{{ __('Payer') }}</label><input class="form-control" name="payer" value="{{ $document->payer }}"></div>@endif<div class="form-group"><label>{{ __('Description') }}</label><textarea class="form-control" name="description">{{ $document->description }}</textarea></div><div class="form-group"><label>{{ __('Edit reason') }}</label><input class="form-control" name="reason" required></div><button class="btn btn-outline-primary">{{ __('Save audited edit') }}</button></form></div></div></div><div class="col-lg-5 mb-3"><div class="card cf-danger-panel"><div class="card-body"><h5 class="card-title">{{ __('Void / reversal') }}</h5><div class="cf-history-notice mb-3">{{ __('Review the posted document above before confirming. The original document and Ledger remain; this creates one append-only reversal.') }}</div><form method="POST" action="{{ route($voidRoute, $document->id) }}">@csrf<div class="form-group"><label>{{ __('Reason') }}</label><textarea class="form-control" name="reason" required></textarea></div><button class="btn btn-warning">{{ __('Void and record reversal') }}</button></form></div></div></div></div>@endif
</div>
@endsection
