@extends('layouts.master')
@section('title', __('Central Finance'))
@section('content')
<div class="content-wrapper">
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-3"><div><small class="text-primary font-weight-bold">{{ __('Central Finance') }} / {{ __('报销申请') }}</small><h4 class="mb-0">{{ $document->reference_no ?: __('Reimbursement request') }}</h4><span class="text-muted">{{ __('当前校区：').$school->name }}</span></div><a class="btn btn-outline-secondary mt-2 mt-md-0" href="{{ route('central-finance.reimbursements.index') }}">{{ __('Back to list') }}</a></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="row"><div class="col-lg-7 mb-3"><div class="card"><div class="card-body"><h5>{{ __('Request details') }}</h5><dl class="row mb-0"><dt class="col-sm-4">{{ __('Status') }}</dt><dd class="col-sm-8"><span class="badge badge-{{ $document->status === 'approved' ? 'success' : ($document->status === 'pending' ? 'warning' : 'secondary') }}">{{ __($document->status) }}</span></dd><dt class="col-sm-4">{{ __('Amount') }}</dt><dd class="col-sm-8">{{ number_format($document->amount,2) }} {{ $document->currency }}</dd><dt class="col-sm-4">{{ __('Category') }}</dt><dd class="col-sm-8">{{ $document->category?->name ?: '—' }}</dd><dt class="col-sm-4">{{ __('Description') }}</dt><dd class="col-sm-8">{{ $document->description }}</dd><dt class="col-sm-4">{{ __('Submission reason') }}</dt><dd class="col-sm-8">{{ $document->submission_reason }}</dd><dt class="col-sm-4">{{ __('Linked Expense') }}</dt><dd class="col-sm-8">@if($document->expense_id)<a href="{{ route('central-finance.expenses.show',$document->expense_id) }}">#{{ $document->expense_id }}</a>@else — @endif</dd></dl></div></div></div><div class="col-lg-5 mb-3"><div class="card"><div class="card-body"><h5>{{ __('Audit timeline') }}</h5>@forelse($audits as $audit)<div class="border-left pl-3 pb-2 mb-2"><strong>{{ __($audit->action) }}</strong><div class="small text-muted">{{ $audit->created_at?->format('Y-m-d H:i') }} · {{ $audit->reason ?: __('System recorded') }}</div></div>@empty<p class="text-muted mb-0">{{ __('No audit history found.') }}</p>@endforelse</div></div></div></div>
    @if($document->status === 'pending' && !$writeDisabled)
        <div class="row">
            @if($canApprove)
                <div class="col-lg-6 mb-3"><div class="card"><div class="card-body"><h5>{{ __('Approve') }}</h5><form method="POST" action="{{ route('central-finance.reimbursements.approve', $document->id) }}" data-lifecycle-confirm data-lifecycle-object="{{ $document->reference_no ?: __('Reimbursement request') }}" data-lifecycle-amount="{{ number_format($document->amount, 2) }} {{ $document->currency }}" data-lifecycle-current-status="{{ __('Pending') }}" data-lifecycle-result="{{ __('Approved · one Expense will be created') }}">@csrf<div class="form-group"><select name="fund_account_id" class="form-control" required><option value="">{{ __('Fund Account') }}</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->account_name }}</option>@endforeach</select></div><div class="form-group"><input name="payment_method" class="form-control" value="Cash" required></div><div class="form-group"><input name="reason" class="form-control" placeholder="{{ __('Approval reason') }}" required></div><button class="btn btn-theme">{{ __('Approve and create Expense') }}</button></form></div></div></div>
                <div class="col-lg-6 mb-3"><div class="card cf-danger-panel"><div class="card-body"><h5>{{ __('Reject or cancel') }}</h5><form method="POST" action="{{ route('central-finance.reimbursements.reject', $document->id) }}" class="mb-2" data-lifecycle-confirm data-lifecycle-object="{{ $document->reference_no ?: __('Reimbursement request') }}" data-lifecycle-amount="{{ number_format($document->amount, 2) }} {{ $document->currency }}" data-lifecycle-current-status="{{ __('Pending') }}" data-lifecycle-result="{{ __('Rejected · no Expense or Ledger entry will be created') }}">@csrf<input name="reason" class="form-control mb-2" placeholder="{{ __('Reject reason') }}" required><button class="btn btn-outline-danger">{{ __('Reject') }}</button></form><form method="POST" action="{{ route('central-finance.reimbursements.cancel', $document->id) }}" data-lifecycle-confirm data-lifecycle-object="{{ $document->reference_no ?: __('Reimbursement request') }}" data-lifecycle-amount="{{ number_format($document->amount, 2) }} {{ $document->currency }}" data-lifecycle-current-status="{{ __('Pending') }}" data-lifecycle-result="{{ __('Cancelled · no Expense or Ledger entry will be created') }}">@csrf<input name="reason" class="form-control mb-2" placeholder="{{ __('Cancel reason') }}" required><button class="btn btn-outline-secondary">{{ __('Cancel') }}</button></form></div></div></div>
            @endif
            @if($canWithdraw)
                <div class="col-lg-6 mb-3"><div class="card cf-danger-panel"><div class="card-body"><h5>{{ __('Withdraw') }}</h5><form method="POST" action="{{ route('central-finance.reimbursements.withdraw', $document->id) }}" data-lifecycle-confirm data-lifecycle-object="{{ $document->reference_no ?: __('Reimbursement request') }}" data-lifecycle-amount="{{ number_format($document->amount, 2) }} {{ $document->currency }}" data-lifecycle-current-status="{{ __('Pending') }}" data-lifecycle-result="{{ __('Withdrawn · no Expense or Ledger entry will be created') }}">@csrf<input name="reason" class="form-control mb-2" placeholder="{{ __('Withdrawal reason') }}" required><button class="btn btn-outline-secondary">{{ __('Withdraw request') }}</button></form></div></div></div>
            @endif
        </div>
    @endif
</div>
<x-central-finance.lifecycle-confirmation />
@endsection
