@extends('layouts.master')
@section('title', __('Student Discount Requests'))
@section('content')
<div class="content-wrapper central-finance-page">
    <x-central-finance.page-header :title="__('Student Discount Requests')" :description="__('Front Desk requests cannot change money until Head Finance approves the exact requested terms. No amount may be edited here.')" eyebrow="{{ __('学生收费') }}" />
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="GET" class="mb-3"><label class="mb-0"><input type="checkbox" name="include_qa_test" value="1" @checked($includeQaTest)> {{ __('Include QA/Test requests') }}</label><button class="btn btn-sm btn-outline-primary ml-2">{{ __('Apply') }}</button></form>
    <div class="card"><div class="card-body"><div class="table-responsive"><table class="table"><thead><tr><th>{{ __('School / Student') }}</th><th>{{ __('Fee Item') }}</th><th>{{ __('Gross') }}</th><th>{{ __('Requested Discount') }}</th><th>{{ __('Net') }}</th><th>{{ __('Reason') }}</th><th>{{ __('Business date') }}</th><th>{{ __('Action') }}</th></tr></thead><tbody>@forelse($requests as $request)<tr><td>{{ $request->school?->name ?: __('School') }}<br><small class="text-muted">{{ $request->studentProfile?->student_name ?: __('Student') }} · {{ $request->studentProfile?->student_code ?: $request->student_profile_id }}</small></td><td>#{{ $request->fees_class_type_id }}</td><td>{{ number_format((float) $request->gross_amount_snapshot,2) }} {{ $request->currency_snapshot }}</td><td>{{ __($request->discount_type) }} {{ number_format((float) $request->discount_value,2) }}</td><td>{{ $request->discount_type === 'fixed' ? number_format((float) $request->gross_amount_snapshot - (float) $request->discount_value,2).' '.$request->currency_snapshot : __('Calculated from gross at confirmation') }}</td><td>{{ $request->reason }}</td><td>{{ $request->effective_date?->format('Y-m-d') }}</td><td><form class="d-inline" method="POST" action="{{ route('central-finance.student-discount-requests.approve',$request->id) }}">@csrf<button class="btn btn-sm btn-success" type="submit">{{ __('Approve exact request') }}</button></form><form class="d-inline ml-1" method="POST" action="{{ route('central-finance.student-discount-requests.reject',$request->id) }}">@csrf<input class="form-control form-control-sm d-inline-block" style="width:180px" name="rejection_reason" required placeholder="{{ __('Rejection reason') }}"><button class="btn btn-sm btn-outline-danger" type="submit">{{ __('Reject') }}</button></form></td></tr>@empty<tr><td colspan="8" class="text-muted text-center">{{ __('No pending student Discount requests.') }}</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
