@extends('layouts.master')

@section('title', __('Central Finance'))

@section('css')
<style>
    .central-finance-context { border: 1px solid #e4e7ed; border-radius: .45rem; background: #fff; padding: .65rem .85rem; }
    .central-finance-context .form-control { min-width: 190px; }
    .central-finance-nav { position: sticky; top: 80px; }
    .central-finance-nav .nav-link { color: #4b5563; padding: .52rem .7rem; border-radius: .35rem; }
    .central-finance-nav .nav-link.active { background: #1f5f87; color: #fff; }
    .central-finance-nav .nav-label { color: #8a94a6; font-size: .72rem; font-weight: 700; letter-spacing: .04em; margin: .9rem .7rem .3rem; text-transform: uppercase; }
    .central-finance-form-card { max-width: 760px; }
    .central-finance-form-card .form-control { min-height: 38px; }
    @media (max-width: 991.98px) { .central-finance-nav { position: static; margin-bottom: 1rem; } .central-finance-nav .nav { flex-direction: row !important; flex-wrap: wrap; } }
    @media (max-width: 575.98px) { .central-finance-context .form-control { min-width: 0; width: 100%; } }
</style>
@endsection

@section('content')
@php($operation = in_array(request('operation'), ['expense', 'income', 'reimbursement'], true) ? request('operation') : 'expense')
@php($showWriteForm = !$school || $canOperate)
@php($writeDisabled = !$school)
@php($writeAvailabilityMessage = __('Select an authorized School before recording a Central Finance transaction.'))
<div class="content-wrapper">
    <h1 class="sr-only">{{ __('Central Finance') }}</h1>
    <div class="central-finance-context d-flex flex-wrap align-items-center justify-content-between mb-3">
        <div class="mr-3 mb-2 mb-md-0">
            <small class="text-muted d-block">{{ __('Central Finance') }}</small>
            <strong>@if($school)<span class="sr-only">{{ __('Operating School:') }}</span>{{ __('当前操作校区：').$school->name }}@else{{ __('All Schools · Read-only') }}@endif</strong>
        </div>
        <div class="d-flex flex-wrap align-items-center">
            <form method="POST" action="{{ route('central-finance.school.enter') }}" class="mr-2 mb-1">@csrf
                <select name="school_id" class="form-control form-control-sm" onchange="this.form.submit()" aria-label="{{ __('Switch School') }}">
                    <option value="">{{ __('切换校区') }}</option>
                    @foreach($schools as $availableSchool)<option value="{{ $availableSchool->id }}" @selected($school && $school->id === $availableSchool->id)>{{ $availableSchool->name }}</option>@endforeach
                </select>
            </form>
            @if($school)<form method="POST" action="{{ route('central-finance.school.exit') }}" class="mb-1">@csrf<button class="btn btn-sm btn-outline-secondary">{{ __('返回全部校区') }}</button></form>@endif
        </div>
    </div>

    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if(!$school)<div class="alert alert-info">{{ __('All Schools shows consolidated Central Finance only. Select an authorized School to create or resolve financial documents.') }}</div>@endif
    @if($school && !$canOperate)<div class="alert alert-warning">{{ $cutoverStatus !== 'central' ? __('This School remains in legacy Finance until its approved Central cutover. Central Finance is read-only.') : __('You can view this School, but you do not have Central Finance operating authority.') }}</div>@endif

    <div class="row">
        <aside class="col-lg-3 col-xl-2">
            <div class="card"><div class="card-body p-2 central-finance-nav">
                <nav class="nav nav-pills flex-column" aria-label="{{ __('Central Finance navigation') }}">
                    <span class="nav-label">{{ __('财务总览') }}</span>
                    <a class="nav-link {{ $page === 'dashboard' ? 'active' : '' }}" href="{{ route('central-finance.dashboard') }}">{{ __('财务总览') }}</a>
                    <span class="nav-label">{{ __('收支管理') }}</span>
                    <a class="nav-link {{ $page === 'receivables' ? 'active' : '' }}" href="{{ route('central-finance.receivables') }}">{{ __('学生收费') }}</a>
                    <a class="nav-link {{ $page === 'payments' ? 'active' : '' }}" href="{{ route('central-finance.payments.index') }}">{{ __('收费记录 / 收据') }}</a>
                    <a class="nav-link {{ $page === 'student-ledger' ? 'active' : '' }}" href="{{ route('central-finance.student-ledger') }}">{{ __('学生账本') }}</a>
                    <a class="nav-link {{ $page === 'operating' && $operation === 'income' ? 'active' : '' }}" href="{{ route('central-finance.operations', ['operation' => 'income']) }}">{{ __('其他收入') }}</a>
                    <a class="nav-link {{ $page === 'operating' && $operation === 'expense' ? 'active' : '' }}" href="{{ route('central-finance.operations', ['operation' => 'expense']) }}">{{ __('支出管理') }}</a>
                    <a class="nav-link {{ $page === 'operating' && $operation === 'reimbursement' ? 'active' : '' }}" href="{{ route('central-finance.operations', ['operation' => 'reimbursement']) }}">{{ __('报销申请') }}</a>
                    <span class="nav-label">{{ __('资金管理') }}</span>
                    <a class="nav-link {{ $page === 'accounts' ? 'active' : '' }}" href="{{ route('central-finance.accounts') }}">{{ __('银行账户') }}</a>
                    <a class="nav-link {{ $page === 'transfers' ? 'active' : '' }}" href="{{ route('central-finance.transfers') }}">{{ __('银行转账') }}</a>
                    <a class="nav-link {{ $page === 'handovers' ? 'active' : '' }}" href="{{ route('central-finance.handovers') }}">{{ __('资金交接') }}</a>
                    <a class="nav-link {{ $page === 'funding' ? 'active' : '' }}" href="{{ route('central-finance.funding') }}">{{ __('总部拨款') }}</a>
                    <span class="nav-label">{{ __('财务报表') }}</span>
                    <a class="nav-link {{ $page === 'reports' ? 'active' : '' }}" href="{{ route('central-finance.reports') }}">{{ __('财务报表') }}</a>
                    <a class="nav-link {{ $page === 'ledger' ? 'active' : '' }}" href="{{ route('central-finance.ledger') }}">{{ __('Standard Ledger') }}</a>
                    @if($canConfigureAccounts)<a class="nav-link {{ $page === 'audits' ? 'active' : '' }}" href="{{ route('central-finance.audits') }}">{{ __('审计记录') }}</a>@endif
                    @if($canConfigureAccounts)<span class="nav-label">{{ __('Central Finance 设置') }}</span><a class="nav-link {{ $page === 'accounts' ? 'active' : '' }}" href="{{ route('central-finance.accounts') }}#central-finance-setup">{{ __('账户与开账设置') }}</a><a class="nav-link {{ $page === 'staff' ? 'active' : '' }}" href="{{ route('central-finance.staff') }}">{{ __('财务人员') }}</a><a class="nav-link {{ $page === 'categories' ? 'active' : '' }}" href="{{ route('central-finance.categories') }}">{{ __('财务分类') }}</a>@endif
                </nav>
            </div></div>
        </aside>

        <main class="col-lg-9 col-xl-10">
            @if(in_array($page, ['dashboard', 'reports'], true))
                <div class="row">
                    @foreach(['money_in'=>'Money In','money_out'=>'Money Out','operating_income'=>'Operating Income','operating_expense'=>'Operating Expense','operating_net'=>'Operating Net'] as $key=>$label)
                        <div class="col-sm-6 col-xl"><div class="card mb-3"><div class="card-body"><small class="text-muted">{{ __($label) }}</small><h4 class="mb-0">{{ number_format($totals[$key], 2) }}</h4></div></div></div>
                    @endforeach
                </div>
                <div class="card"><div class="card-body"><h5>{{ $page === 'reports' ? __('财务报表') : __('财务总览') }}</h5><p class="text-muted mb-0">{{ __('Totals are derived exclusively from the append-only Central Standard Ledger. Internal transfers remain excluded from operating results.') }}</p></div></div>
            @endif

            @if($page === 'receivables')
                <div class="card central-finance-form-card mb-3"><div class="card-body"><h5>{{ __('学生收费') }}</h5><p class="text-muted">{{ __('Student identity is read only from Central Student Financial Profiles synchronized from the School tenant.') }}</p>
                    @if(!$school)
                        <div class="alert alert-info mb-3">{{ __('All Schools is read-only for payment history and totals. Please select a School to collect a payment.') }}</div>
                        <div class="row"><div class="col-md-4"><div class="border rounded p-2"><small class="text-muted">{{ __('Money In') }}</small><strong class="d-block">{{ number_format($totals['money_in'], 2) }}</strong></div></div><div class="col-md-4"><div class="border rounded p-2"><small class="text-muted">{{ __('Operating Income') }}</small><strong class="d-block">{{ number_format($totals['operating_income'], 2) }}</strong></div></div><div class="col-md-4"><div class="border rounded p-2"><small class="text-muted">{{ __('Payment History') }}</small><strong class="d-block">{{ $payments->total() }}</strong></div></div></div>
                    @elseif($canOperate)
                        <form method="GET" action="{{ route('central-finance.receivables') }}" class="form-row align-items-end mb-3" id="central-payment-filters">
                            <div class="form-group col-md-4"><label for="central-payment-class">{{ __('Class') }}</label><select name="payment_class" id="central-payment-class" class="form-control"><option value="">{{ __('All Classes') }}</option>@foreach($paymentClasses as $class)<option value="{{ $class }}" @selected(($filters['payment_class'] ?? '') === $class)>{{ $class }}</option>@endforeach</select></div>
                            <div class="form-group col-md-5"><label for="central-payment-search">{{ __('Student search') }}</label><input type="search" name="payment_student" id="central-payment-search" class="form-control" value="{{ $filters['payment_student'] ?? '' }}" placeholder="{{ __('Name or student number') }}"></div>
                            <div class="form-group col-md-3"><button class="btn btn-outline-primary btn-block">{{ __('Filter Students') }}</button></div>
                        </form>
                        <form method="POST" action="{{ route('central-finance.payments.store') }}" id="central-payment-form">@csrf
                            <div class="form-group"><label>{{ __('Student') }}</label><select id="central-payment-student" class="form-control" required><option value="">{{ __('Select Student') }}</option>@foreach($paymentProfiles as $profile)<option value="{{ $profile->id }}" data-name="{{ $profile->student_name }}" data-admission-no="{{ $profile->admission_no }}" data-class="{{ trim(($profile->class_name ?? '').(($profile->section_name ?? '') ? ' · '.$profile->section_name : '')) }}" data-due="{{ $profile->total_due ?? 0 }}" data-paid="{{ $profile->total_paid ?? 0 }}">{{ $profile->student_name }}{{ $profile->admission_no ? ' · '.$profile->admission_no : '' }}</option>@endforeach</select></div>
                            <div id="central-payment-student-summary" class="border rounded p-3 mb-3 d-none" aria-live="polite"><div class="row"><div class="col-md-4"><strong id="central-payment-summary-name"></strong><span id="central-payment-summary-admission" class="d-block text-muted small"></span><span id="central-payment-summary-class" class="d-block text-muted small"></span></div><div class="col-md-2"><small class="text-muted d-block">{{ __('Total due') }}</small><strong id="central-payment-summary-due"></strong></div><div class="col-md-2"><small class="text-muted d-block">{{ __('Paid') }}</small><strong id="central-payment-summary-paid"></strong></div><div class="col-md-2"><small class="text-muted d-block">{{ __('Outstanding') }}</small><strong id="central-payment-summary-outstanding"></strong></div><div class="col-md-2"><small class="text-muted d-block">{{ __('Pending items') }}</small><strong id="central-payment-summary-items"></strong></div></div></div>
                            <div class="form-group"><label>{{ __('Outstanding Receivable') }}</label><select name="receivable_id" id="central-payment-receivable" class="form-control" required disabled><option value="">{{ __('Select Student first') }}</option>@foreach($paymentReceivables as $r)<option value="{{ $r->id }}" data-student-id="{{ $r->student_profile_id }}" data-outstanding="{{ $r->amount_due - $r->amount_paid }}">{{ $r->description }} · {{ number_format($r->amount_due - $r->amount_paid,2) }} {{ $r->currency }}</option>@endforeach</select><small id="central-payment-empty" class="form-text text-muted d-none">{{ __('当前没有待缴项目') }}</small></div>
                            <div class="form-group"><label>{{ __('Fund Account') }}</label><select name="fund_account_id" class="form-control" required><option value="">{{ __('Fund Account') }}</option>@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->account_name }}</option>@endforeach</select></div>
                            <div class="form-row"><div class="form-group col-md-4"><label>{{ __('Amount') }}</label><input name="amount" id="central-payment-amount" type="number" step="0.01" min="0.01" class="form-control" required disabled></div><div class="form-group col-md-4"><label>{{ __('Payment method') }}</label><input name="payment_method" class="form-control" value="Cash" required></div><div class="form-group col-md-4"><label>{{ __('Reference') }}</label><input name="payment_reference" class="form-control"></div></div>
                            <button class="btn btn-theme" id="central-payment-submit" disabled>{{ __('Collect') }}</button>
                        </form>
                        <script>document.addEventListener('DOMContentLoaded',function(){const student=document.getElementById('central-payment-student'),receivable=document.getElementById('central-payment-receivable'),amount=document.getElementById('central-payment-amount'),submit=document.getElementById('central-payment-submit'),empty=document.getElementById('central-payment-empty'),summary=document.getElementById('central-payment-student-summary');if(!student||!receivable)return;const options=[...receivable.querySelectorAll('option[data-student-id]')],fmt=value=>new Intl.NumberFormat(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0));student.addEventListener('change',function(){const id=this.value,selected=this.options[this.selectedIndex];receivable.value='';receivable.disabled=!id;amount.value='';amount.disabled=true;submit.disabled=true;let count=0,outstanding=0;options.forEach(option=>{const visible=option.dataset.studentId===id;option.hidden=!visible;option.disabled=!visible;if(visible){count++;outstanding+=Number(option.dataset.outstanding||0);}});if(id){document.getElementById('central-payment-summary-name').textContent=selected.dataset.name||'';document.getElementById('central-payment-summary-admission').textContent=selected.dataset.admissionNo||'';document.getElementById('central-payment-summary-class').textContent=selected.dataset.class||'—';document.getElementById('central-payment-summary-due').textContent=fmt(selected.dataset.due);document.getElementById('central-payment-summary-paid').textContent=fmt(selected.dataset.paid);document.getElementById('central-payment-summary-outstanding').textContent=fmt(outstanding);document.getElementById('central-payment-summary-items').textContent=count;summary.classList.remove('d-none');}else summary.classList.add('d-none');empty.classList.toggle('d-none',!id||count>0);});receivable.addEventListener('change',function(){const option=this.options[this.selectedIndex];const enabled=!!this.value;amount.disabled=!enabled;submit.disabled=!enabled;if(enabled)amount.max=option.dataset.outstanding;});});</script>
                    @else
                        <div class="alert alert-warning mb-0">{{ __('This School is read-only until Central cutover and operating scope are both active.') }}</div>
                    @endif
                </div></div>
                <div class="card"><div class="card-body"><h5>{{ __('Receivables') }}</h5><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Student') }}</th><th>{{ __('Description') }}</th><th>{{ __('Due') }}</th><th>{{ __('Paid') }}</th><th>{{ __('Status') }}</th></tr></thead><tbody>@foreach($receivables as $r)<tr><td>{{ $r->studentProfile?->student_name }}</td><td>{{ $r->description }}</td><td>{{ number_format($r->amount_due,2) }}</td><td>{{ number_format($r->amount_paid,2) }}</td><td>{{ $r->status }}</td></tr>@endforeach</tbody></table></div>@if(method_exists($receivables,'links'))<div class="mt-3">{{ $receivables->links() }}</div>@endif</div></div>
            @endif

            @if($page === 'operating')
                @if($operation === 'expense')
                    @if($school && $canOperate)
                        <div class="card central-finance-form-card mb-3"><div class="card-body"><h5>{{ __('Central Expense Import') }}</h5><p class="text-muted">{{ __('Expense Import Template V1 posts direct historical Expenses only. 报销人 is Expense history metadata; it never creates or approves a Reimbursement.') }}</p><a class="btn btn-sm btn-outline-secondary mb-3" href="{{ route('central-finance.expense-import.template') }}">{{ __('Download Expense Import Template V1') }}</a><form method="POST" enctype="multipart/form-data" action="{{ route('central-finance.expense-import.preview') }}">@csrf<div class="form-row align-items-end"><div class="form-group col-md-8 mb-md-0"><label>{{ __('Expense Import File') }}</label><input type="file" name="expense_import" class="form-control-file" accept=".xlsx,.xls,.csv" required></div><div class="col-md-4"><button class="btn btn-theme">{{ __('Preview Import') }}</button></div></div></form></div></div>
                        @if($expenseImportBatch)<div class="card mb-3"><div class="card-body"><h5>{{ __('Expense Import Preview') }}</h5><p class="text-muted">{{ __('Valid') }}: {{ $expenseImportBatch->valid_rows }} · {{ __('Errors') }}: {{ $expenseImportBatch->error_rows }} · {{ __('Status') }}: {{ $expenseImportBatch->status }}</p><div class="table-responsive"><table class="table table-sm"><thead><tr><th>#</th><th>{{ __('Reference') }}</th><th>{{ __('Expense') }}</th><th>{{ __('Reimbursed by') }}</th><th>{{ __('Validation') }}</th></tr></thead><tbody>@foreach($expenseImportBatch->preview_data ?? [] as $row)<tr><td>{{ $row['row_number'] }}</td><td>{{ $row['data']['reference_no'] }}</td><td>{{ $row['data']['amount'] }}</td><td>{{ $row['data']['reimbursed_by'] }}</td><td>@if($row['status'] === 'valid')<span class="text-success">{{ __('Valid') }}</span>@else<span class="text-danger">{{ implode('; ', $row['errors']) }}</span>@endif</td></tr>@endforeach</tbody></table></div>@if($expenseImportBatch->status === 'pending' && $expenseImportBatch->error_rows === 0)<form method="POST" action="{{ route('central-finance.expense-import.confirm', $expenseImportBatch->token) }}">@csrf<button class="btn btn-theme">{{ __('Confirm Expense Import') }}</button></form>@endif</div></div>@endif
                    @endif
                    <div class="card central-finance-form-card"><div class="card-body"><h5>{{ __('支出管理') }}</h5>@if($showWriteForm)@if($writeDisabled)<p class="text-muted mb-3">{{ $writeAvailabilityMessage }}</p>@endif<form method="POST" action="{{ route('central-finance.expenses.store') }}">@csrf<fieldset @disabled($writeDisabled)>@include('central-finance.partials.operation-form',['categories'=>$expenseCategories,'actionLabel'=>'Record Expense','payer'=>false])</fieldset></form>@endif</div></div>
                @elseif($operation === 'income')
                    <div class="card central-finance-form-card"><div class="card-body"><h5>{{ __('其他收入') }}</h5>@if($showWriteForm)@if($writeDisabled)<p class="text-muted mb-3">{{ $writeAvailabilityMessage }}</p>@endif<form method="POST" action="{{ route('central-finance.other-income.store') }}">@csrf<fieldset @disabled($writeDisabled)>@include('central-finance.partials.operation-form',['categories'=>$incomeCategories,'actionLabel'=>'Record Other Income','payer'=>true])</fieldset></form>@endif</div></div>
                @else
                    <div class="card central-finance-form-card"><div class="card-body"><h5>{{ __('报销申请') }}</h5>@if($showWriteForm)@if($writeDisabled)<p class="text-muted mb-3">{{ $writeAvailabilityMessage }}</p>@endif<form method="POST" action="{{ route('central-finance.reimbursements.store') }}">@csrf<fieldset @disabled($writeDisabled)>
                        <div class="form-group"><select name="category_id" class="form-control" required><option value="">{{ __('Expense Category') }}</option>@foreach($expenseCategories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div><div class="form-group"><input name="amount" type="number" step="0.01" class="form-control" placeholder="{{ __('Amount') }}" required></div><div class="form-group"><input name="currency" class="form-control" value="MMK" required></div><div class="form-group"><input name="reference_no" class="form-control" placeholder="{{ __('Reference') }}"></div><div class="form-group"><textarea name="description" class="form-control" placeholder="{{ __('Description') }}"></textarea></div><button class="btn btn-theme">{{ __('Submit Reimbursement') }}</button>
                    </fieldset></form>@endif</div></div>
                    <div class="card mt-3"><div class="card-body"><h5>{{ __('Pending reimbursements') }}</h5>@foreach($reimbursements->where('status','pending') as $r)<div class="border rounded p-2 mb-2">{{ $r->reference_no }} · {{ number_format($r->amount,2) }} @if($canOperate)<form class="mt-2" method="POST" action="{{ route('central-finance.reimbursements.approve',$r->id) }}">@csrf <div class="form-row"><div class="col-md-4"><select name="fund_account_id" class="form-control" required>@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->account_name }}</option>@endforeach</select></div><div class="col-md-3"><input name="payment_method" class="form-control" value="Cash" required></div><div class="col-md-3"><input name="reason" class="form-control" placeholder="{{ __('Approval reason') }}" required></div><div class="col-md-2"><button class="btn btn-outline-primary">{{ __('Approve') }}</button></div></div></form>@endif</div>@endforeach</div></div>
                @endif
            @endif

            @if($page === 'accounts')
                @if($canConfigureAccounts)<div class="card central-finance-form-card mb-3" id="central-finance-setup"><div class="card-body"><h5>{{ __('Central Finance 设置') }}</h5><p class="text-muted">{{ __('Only Head Finance may create an opening balance. It is audited and does not create Money In, Operating Income, or a Ledger entry.') }}</p><form method="POST" action="{{ route('central-finance.accounts.store') }}">@csrf
                    <div class="form-row"><div class="form-group col-md-4"><input name="account_code" class="form-control" placeholder="{{ __('Account code') }}" required></div><div class="form-group col-md-4"><input name="account_name" class="form-control" placeholder="{{ __('Account name') }}" required></div><div class="form-group col-md-4"><select name="owner_type" class="form-control" required><option value="school">{{ __('Current School') }}</option><option value="hq">{{ __('HQ') }}</option></select></div><div class="form-group col-md-4"><input name="currency" class="form-control" value="MMK" maxlength="3" required></div><div class="form-group col-md-4"><input name="opening_balance" type="number" step="0.0001" min="0" class="form-control" placeholder="{{ __('Opening balance') }}" required></div><div class="form-group col-md-4"><input name="opening_balance_date" type="date" class="form-control" required></div></div><div class="form-group"><input name="opening_reason" class="form-control" placeholder="{{ __('Signed opening-balance reference / reason') }}" required></div><div class="form-group"><label>{{ __('Authorized Central Finance users') }}</label><div class="d-flex flex-wrap">@foreach($schoolUsers as $user)<label class="mr-3"><input type="checkbox" name="authorized_user_ids[]" value="{{ $user->id }}" @checked($user->id === $actor->id)> {{ $user->first_name }} {{ $user->last_name }}</label>@endforeach</div></div><button class="btn btn-theme">{{ __('Create audited Fund Account') }}</button></form></div></div>
                <details class="card mb-3"><summary class="card-body font-weight-bold">{{ __('Cutover state') }} · {{ $cutoverStatus }}</summary><div class="card-body border-top"><form method="POST" action="{{ route('central-finance.cutover-state') }}" class="form-inline">@csrf <select name="status" class="form-control mr-2"><option value="ready">ready</option><option value="central">central</option><option value="legacy">legacy</option></select><button class="btn btn-outline-primary">{{ __('Update cutover state') }}</button></form></div></details>@endif
                <div class="card"><div class="card-body"><h5>{{ __('银行账户') }}</h5><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Account') }}</th><th>{{ __('Owner') }}</th><th>{{ __('Currency') }}</th><th>{{ __('Money In') }}</th><th>{{ __('Money Out') }}</th><th>{{ __('Balance') }}</th><th>{{ __('Report') }}</th>@if($canConfigureAccounts)<th>{{ __('Configuration') }}</th>@endif</tr></thead><tbody>@foreach($accounts as $a)<tr><td>{{ $a->account_name }}</td><td>{{ $a->owner_type === 'hq' ? 'HQ' : $school?->name }}</td><td>{{ $a->currency }}</td><td>{{ number_format($ledger->where('fund_account_id',$a->id)->sum('money_in'),2) }}</td><td>{{ number_format($ledger->where('fund_account_id',$a->id)->sum('money_out'),2) }}</td><td>{{ number_format($a->opening_balance + $ledger->where('fund_account_id',$a->id)->sum('money_in') - $ledger->where('fund_account_id',$a->id)->sum('money_out'),2) }}</td><td><a class="btn btn-sm btn-outline-secondary" href="{{ route('central-finance.accounts.report',$a->id) }}">{{ __('Details') }}</a></td>@if($canConfigureAccounts)<td>@if(($a->owner_type === 'school' && $school && $a->school_id === $school->id) || ($a->owner_type === 'hq' && $a->school_id === null))<details><summary>{{ __('Manage') }}</summary><form method="POST" action="{{ route('central-finance.accounts.assignments',$a->id) }}" class="mt-2">@csrf @foreach($schoolUsers as $user)<label class="mr-2"><input type="checkbox" name="authorized_user_ids[]" value="{{ $user->id }}" @checked($a->authorizedUsers->contains('id',$user->id))> {{ $user->first_name }}</label>@endforeach <button class="btn btn-sm btn-outline-primary">{{ __('Save') }}</button></form><form method="POST" action="{{ route('central-finance.accounts.opening-adjustments',$a->id) }}" class="mt-2">@csrf <input name="amount" type="number" step="0.0001" class="form-control mb-1" placeholder="{{ __('Signed adjustment') }}" required><input name="effective_date" type="date" class="form-control mb-1" required><input name="reason" class="form-control mb-1" placeholder="{{ __('Adjustment reason') }}" required><button class="btn btn-sm btn-outline-primary">{{ __('Record audited adjustment') }}</button></form></details>@endif</td>@endif</tr>@endforeach</tbody></table></div></div></div>
            @endif

            @if(in_array($page,['transfers','handovers','funding'],true))
                @php($heading = $page === 'transfers' ? __('银行转账') : ($page === 'handovers' ? __('资金交接') : __('总部拨款')))
                <div class="card central-finance-form-card mb-3"><div class="card-body"><h5>{{ $heading }}</h5>@if($showWriteForm)@if($writeDisabled)<p class="text-muted mb-3">{{ $writeAvailabilityMessage }}</p>@endif<form method="POST" action="{{ route('central-finance.'.$page.'.store') }}">@csrf<fieldset @disabled($writeDisabled)>
                    @if($page === 'handovers')<div class="form-group"><label>{{ __('Receiver') }}</label><select name="receiver_user_id" class="form-control" required><option value="">{{ __('Receiver') }}</option>@foreach($schoolUsers as $u)<option value="{{ $u->id }}">{{ $u->first_name }} {{ $u->last_name }}</option>@endforeach</select></div>@endif
                    <div class="form-group"><label>{{ __('Source Account') }}</label><select name="source_account_id" class="form-control" required><option value="">{{ __('Source Account') }}</option>@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->account_name }}</option>@endforeach</select></div><div class="form-group"><label>{{ __('Destination Account') }}</label><select name="destination_account_id" class="form-control" required><option value="">{{ __('Destination Account') }}</option>@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->account_name }}</option>@endforeach</select></div><div class="form-row"><div class="form-group col-md-6"><input name="amount" type="number" step="0.01" min="0.01" class="form-control" placeholder="{{ __('Amount') }}" required></div><div class="form-group col-md-6"><input name="reference_no" class="form-control" placeholder="{{ __('Reference') }}"></div></div><button class="btn btn-theme">{{ __('Submit') }}</button>
                </fieldset></form>@endif</div></div>
                @if($page !== 'transfers')
                    @php($documents = $page === 'handovers' ? $handovers : $fundingRequests)
                    <div class="card"><div class="card-body"><h5>{{ __('Recent requests') }}</h5><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Reference') }}</th><th>{{ __('Amount') }}</th><th>{{ __('Status') }}</th><th>{{ __('Action') }}</th></tr></thead><tbody>
                        @foreach($documents as $document)
                            <tr><td>{{ $document->reference_no }}</td><td>{{ number_format($document->amount,2) }}</td><td>{{ $document->status }}</td><td>
                                @if($canOperate && $document->status === 'pending')
                                    @php($routeParameter = $page === 'handovers' ? ['handover' => $document->id] : ['funding' => $document->id])
                                    @foreach(['confirm'=>'Confirm','reject'=>'Reject','cancel'=>'Cancel'] as $action=>$label)
                                        <form method="POST" action="{{ route('central-finance.'.$page.'.resolve', array_merge($routeParameter, ['action' => $action])) }}" class="d-inline">@csrf
                                            @if($action !== 'confirm')<input name="reason" value="{{ __('Workflow decision') }}" type="hidden">@endif
                                            <button class="btn btn-sm btn-outline-secondary">{{ __($label) }}</button>
                                        </form>
                                    @endforeach
                                @endif
                            </td></tr>
                        @endforeach
                    </tbody></table></div></div></div>
                @endif
            @endif

            @if($page === 'student-ledger')
                <div class="card"><div class="card-body"><h5>{{ __('学生账本') }}</h5><form method="GET" class="form-row mb-3"><div class="col-md-5"><input class="form-control" name="student" value="{{ $filters['student'] ?? '' }}" placeholder="{{ __('Student name or admission number') }}"></div><div class="col-md-2"><button class="btn btn-outline-primary">{{ __('Search') }}</button></div></form><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Student') }}</th><th>{{ __('Admission') }}</th><th>{{ __('Due') }}</th><th>{{ __('Paid') }}</th><th>{{ __('Outstanding') }}</th><th>{{ __('Last receipt') }}</th></tr></thead><tbody>@foreach($profiles as $profile) @php($due=(float)$profile->receivables->sum('amount_due')) @php($paid=(float)$profile->receivables->sum('amount_paid')) <tr><td>{{ $profile->student_name }}</td><td>{{ $profile->admission_no }}</td><td>{{ number_format($due,2) }}</td><td>{{ number_format($paid,2) }}</td><td>{{ number_format($due-$paid,2) }}</td><td>{{ optional($payments->first(fn($payment) => $payment->receivable?->student_profile_id === $profile->id)?->receipt)->receipt_no }}</td></tr> @endforeach</tbody></table></div>@if(method_exists($profiles,'links'))<div class="mt-3">{{ $profiles->links() }}</div>@endif</div></div>
            @endif

            @if($page === 'payments')
                @if($school && $canOperate)
                    <div class="card central-finance-form-card mb-3"><div class="card-body"><h5>{{ __('Central Payment Import') }}</h5>
                        <p class="text-muted">{{ __('Payment Import Template V1 matches existing Central Students, Receivables, and authorized active Fund Accounts. Preview does not create payments, receipts, Ledger entries, or balance changes.') }}</p>
                        <a class="btn btn-sm btn-outline-secondary mb-3" href="{{ route('central-finance.payment-import.template') }}">{{ __('Download Payment Import Template V1') }}</a>
                        <form method="POST" enctype="multipart/form-data" action="{{ route('central-finance.payment-import.preview') }}">@csrf
                            <div class="form-row align-items-end"><div class="form-group col-md-8 mb-md-0"><label>{{ __('Payment Import File') }}</label><input type="file" name="payment_import" class="form-control-file" accept=".xlsx,.xls,.csv" required></div><div class="col-md-4"><button class="btn btn-theme">{{ __('Preview Import') }}</button></div></div>
                        </form>
                    </div></div>
                    @if($paymentImportBatch)
                        <div class="card mb-3"><div class="card-body"><h5>{{ __('Payment Import Preview') }}</h5><p class="text-muted">{{ __('Valid') }}: {{ $paymentImportBatch->valid_rows }} · {{ __('Errors') }}: {{ $paymentImportBatch->error_rows }} · {{ __('Status') }}: {{ $paymentImportBatch->status }}</p>
                            <div class="table-responsive"><table class="table table-sm"><thead><tr><th>#</th><th>{{ __('Student') }}</th><th>{{ __('Receivable') }}</th><th>{{ __('Amount') }}</th><th>{{ __('Reference') }}</th><th>{{ __('Validation') }}</th></tr></thead><tbody>@foreach($paymentImportBatch->preview_data ?? [] as $row)<tr><td>{{ $row['row_number'] }}</td><td>{{ $row['data']['student_uuid'] ?: $row['data']['student_code'] }}</td><td>{{ $row['data']['receivable_reference'] }}</td><td>{{ $row['data']['amount'] }}</td><td>{{ $row['data']['payment_reference'] }}</td><td>@if($row['status'] === 'valid')<span class="text-success">{{ __('Valid') }}</span>@else<span class="text-danger">{{ implode('; ', $row['errors']) }}</span>@endif</td></tr>@endforeach</tbody></table></div>
                            @if($paymentImportBatch->status === 'pending' && $paymentImportBatch->error_rows === 0)<form method="POST" action="{{ route('central-finance.payment-import.confirm', $paymentImportBatch->token) }}">@csrf<button class="btn btn-theme">{{ __('Confirm Payment Import') }}</button></form>@endif
                        </div></div>
                    @endif
                @endif
                <div class="card"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">{{ __('收费记录 / 收据') }}</h5><div><a class="btn btn-sm btn-outline-secondary" href="{{ route('central-finance.payments.export', array_merge(request()->query(), ['format' => 'csv'])) }}">CSV</a><a class="btn btn-sm btn-outline-primary" href="{{ route('central-finance.payments.export', array_merge(request()->query(), ['format' => 'xlsx'])) }}">XLSX</a></div></div><form method="GET" class="form-row mb-3"><div class="col-md-2"><input type="date" class="form-control" name="from" value="{{ $filters['from'] ?? '' }}"></div><div class="col-md-2"><input type="date" class="form-control" name="to" value="{{ $filters['to'] ?? '' }}"></div>@if(!$school)<div class="col-md-2"><select class="form-control" name="school_id"><option value="">{{ __('All Schools') }}</option>@foreach($schools as $availableSchool)<option value="{{ $availableSchool->id }}" @selected(($filters['school_id'] ?? null) == $availableSchool->id)>{{ $availableSchool->name }}</option>@endforeach</select></div>@endif<div class="col-md-2"><select class="form-control" name="fund_account_id"><option value="">{{ __('All accounts') }}</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(($filters['fund_account_id'] ?? null) == $account->id)>{{ $account->account_name }}</option>@endforeach</select></div><div class="col-md-2"><input class="form-control" name="student" value="{{ $filters['student'] ?? '' }}" placeholder="{{ __('Student') }}"></div><div class="col-md-2"><input class="form-control" name="reference" value="{{ $filters['reference'] ?? '' }}" placeholder="{{ __('Payment reference') }}"></div><div class="col-md-2 mt-2"><button class="btn btn-outline-primary">{{ __('Filter') }}</button></div></form><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Student') }}</th><th>{{ __('Amount') }}</th><th>{{ __('Fund Account') }}</th><th>{{ __('Reference') }}</th><th>{{ __('Receipt') }}</th></tr></thead><tbody>@foreach($payments as $payment)<tr><td>{{ $payment->paid_at }}</td><td>{{ $payment->receivable?->studentProfile?->student_name }}</td><td>{{ number_format($payment->amount,2) }} {{ $payment->currency }}</td><td>{{ $payment->fundAccount?->account_name }}</td><td>{{ $payment->payment_reference }}</td><td>{{ $payment->receipt?->receipt_no }}</td></tr>@endforeach</tbody></table></div>@if(method_exists($payments,'links'))<div class="mt-3">{{ $payments->links() }}</div>@endif</div></div>
            @endif

            @if($page === 'staff')
                <div class="card"><div class="card-body">
                    <h5>{{ __('Central Finance Staff') }}</h5>
                    <p class="text-muted">{{ __('School Scope is configured by Central Super Admin in Finance Groups. Fund Account Scope is configured by Head Finance from the relevant Fund Account.') }}</p>
                    @if(!$canConfigureAccounts)
                        <div class="alert alert-warning mb-0">{{ __('Select a School where you are authorized as Head Finance to view configuration details.') }}</div>
                    @else
                        <div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Name') }}</th><th>{{ __('Email') }}</th><th>{{ __('School Scope') }}</th><th>{{ __('Fund Account Scope') }}</th></tr></thead><tbody>
                            @foreach($staff as $member)
                                <tr><td>{{ $member->full_name }}</td><td>{{ $member->email }}</td><td>{{ __('View / operate as granted by Central Super Admin') }}</td><td>{{ $member->authorizedFundAccounts->pluck('account_name')->implode(', ') ?: __('None') }}</td></tr>
                            @endforeach
                        </tbody></table></div>
                        @if(method_exists($staff, 'links'))<div class="mt-3">{{ $staff->links() }}</div>@endif
                    @endif
                </div></div>
            @endif

            @if($page === 'categories')
                <div class="card central-finance-form-card mb-3"><div class="card-body"><h5>{{ __('Income / Expense Categories') }}</h5>@if($canConfigureAccounts)<form method="POST" action="{{ route('central-finance.categories.store') }}" class="form-row">@csrf <div class="col-md-3"><select class="form-control" name="type"><option value="income">{{ __('Income') }}</option><option value="expense">{{ __('Expense') }}</option></select></div><div class="col-md-6"><input class="form-control" name="name" placeholder="{{ __('Category name') }}" required></div><div class="col-md-3"><button class="btn btn-theme">{{ __('Add category') }}</button></div></form>@else<div class="alert alert-warning mb-0">{{ __('Only an authorized Head Finance can manage categories.') }}</div>@endif</div></div><div class="card"><div class="card-body"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Type') }}</th><th>{{ __('Category') }}</th><th>{{ __('Status') }}</th>@if($canConfigureAccounts)<th>{{ __('Action') }}</th>@endif</tr></thead><tbody>@foreach($categories as $category)<tr><td>{{ $category->type }}</td><td>{{ $category->name }}</td><td>{{ $category->is_active ? __('Active') : __('Inactive') }}</td>@if($canConfigureAccounts)<td><form method="POST" action="{{ route('central-finance.categories.toggle',$category->id) }}">@csrf<button class="btn btn-sm btn-outline-secondary">{{ $category->is_active ? __('Deactivate') : __('Activate') }}</button></form></td>@endif</tr>@endforeach</tbody></table></div></div></div>
            @endif

            @if($page === 'account-report' && $accountReport)
                <div class="card"><div class="card-body"><div class="d-flex justify-content-between align-items-center"><h5>{{ __('Fund Account Report') }} · {{ $accountReport->account_name }}</h5><div><a class="btn btn-sm btn-outline-secondary" href="{{ route('central-finance.accounts.report.export', array_merge(request()->query(), ['fundAccount' => $accountReport->id, 'format' => 'csv'])) }}">CSV</a><a class="btn btn-sm btn-outline-primary" href="{{ route('central-finance.accounts.report.export', array_merge(request()->query(), ['fundAccount' => $accountReport->id, 'format' => 'xlsx'])) }}">XLSX</a></div></div><p class="text-muted">{{ __('Opening balance') }}: {{ number_format($accountReport->opening_balance,2) }} {{ $accountReport->currency }}</p><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('Source') }}</th><th>{{ __('Reference') }}</th><th>{{ __('Money In') }}</th><th>{{ __('Money Out') }}</th><th>{{ __('Operating Income') }}</th><th>{{ __('Operating Expense') }}</th></tr></thead><tbody>@foreach($ledger as $entry)<tr><td>{{ $entry->entry_date }}</td><td>{{ $entry->source_type }}</td><td>{{ $entry->reference_no }}</td><td>{{ number_format($entry->money_in,2) }}</td><td>{{ number_format($entry->money_out,2) }}</td><td>{{ number_format($entry->operating_income,2) }}</td><td>{{ number_format($entry->operating_expense,2) }}</td></tr>@endforeach</tbody></table></div>{{ $ledger->links() }}</div></div>
            @endif

            @if($page === 'audits')
                <div class="card"><div class="card-body"><h5>{{ __('审计记录') }}</h5><form method="GET" class="form-row mb-3"><div class="col-md-4"><input class="form-control" name="source" value="{{ $filters['source'] ?? '' }}" placeholder="{{ __('Document type') }}"></div><div class="col-md-2"><button class="btn btn-outline-primary">{{ __('Filter') }}</button></div></form><div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('When') }}</th><th>{{ __('Document') }}</th><th>{{ __('Action') }}</th><th>{{ __('Actor') }}</th><th>{{ __('Reason') }}</th></tr></thead><tbody>@foreach($audits as $audit)<tr><td>{{ $audit->created_at }}</td><td>{{ $audit->document_type }} #{{ $audit->document_id }}</td><td>{{ $audit->action }}</td><td>{{ $audit->actor_id }}</td><td>{{ $audit->reason }}</td></tr>@endforeach</tbody></table></div>@if(method_exists($audits,'links'))<div class="mt-3">{{ $audits->links() }}</div>@endif</div></div>
            @endif

            @if($page === 'ledger')
                <div class="card"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">{{ __('Standard Ledger') }}</h5><div><a class="btn btn-sm btn-outline-secondary" href="{{ route('central-finance.ledger.export', array_merge(request()->query(), ['format' => 'csv'])) }}">CSV</a><a class="btn btn-sm btn-outline-primary" href="{{ route('central-finance.ledger.export', array_merge(request()->query(), ['format' => 'xlsx'])) }}">XLSX</a></div></div>
                    <form method="GET" class="form-row mb-3">
                        <div class="col-md-2"><input type="date" class="form-control" name="from" value="{{ $filters['from'] ?? '' }}"></div>
                        <div class="col-md-2"><input type="date" class="form-control" name="to" value="{{ $filters['to'] ?? '' }}"></div>
                        @if(!$school)<div class="col-md-2"><select class="form-control" name="school_id"><option value="">{{ __('All Schools') }}</option>@foreach($schools as $availableSchool)<option value="{{ $availableSchool->id }}" @selected(($filters['school_id'] ?? null) == $availableSchool->id)>{{ $availableSchool->name }}</option>@endforeach</select></div>@endif
                        <div class="col-md-2"><select class="form-control" name="fund_account_id"><option value="">{{ __('All accounts') }}</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(($filters['fund_account_id'] ?? null) == $account->id)>{{ $account->account_name }}</option>@endforeach</select></div>
                        <div class="col-md-2"><select class="form-control" name="category_id"><option value="">{{ __('All categories') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id'] ?? null) == $category->id)>{{ $category->type }} · {{ $category->name }}</option>@endforeach</select></div>
                        <div class="col-md-2"><select class="form-control" name="operator_id"><option value="">{{ __('All operators') }}</option>@foreach($operators as $operator)<option value="{{ $operator->id }}" @selected(($filters['operator_id'] ?? null) == $operator->id)>{{ $operator->full_name }}</option>@endforeach</select></div>
                        <div class="col-md-2"><input class="form-control" name="source" value="{{ $filters['source'] ?? '' }}" placeholder="{{ __('Source type') }}"></div>
                        <div class="col-md-2 mt-2"><button class="btn btn-outline-primary">{{ __('Filter') }}</button></div>
                    </form>
                    <div class="table-responsive"><table class="table mb-0"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('School') }}</th><th>{{ __('Source') }}</th><th>{{ __('Fund Account') }}</th><th>{{ __('Money In') }}</th><th>{{ __('Money Out') }}</th><th>{{ __('Operating Income') }}</th><th>{{ __('Operating Expense') }}</th><th>{{ __('Operator') }}</th></tr></thead><tbody>@foreach($ledger as $entry)<tr><td>{{ $entry->entry_date }}</td><td>{{ $entry->school_id }}</td><td>{{ $entry->source_type }} · {{ $entry->reference_no }}</td><td>{{ $entry->fund_account_id }}</td><td>{{ number_format($entry->money_in,2) }}</td><td>{{ number_format($entry->money_out,2) }}</td><td>{{ number_format($entry->operating_income,2) }}</td><td>{{ number_format($entry->operating_expense,2) }}</td><td>{{ $entry->created_by }}</td></tr>@endforeach</tbody></table></div>{{ $ledger->links() }}
                </div></div>
            @endif
        </main>
    </div>
</div>
@endsection
