@extends('layouts.master')
@section('title', __('Group Finance Reports'))
@section('content')
<div class="content-wrapper"><div class="page-header"><h3 class="page-title">{{ $financeGroup->name }} — {{ __('Finance Reports') }}</h3></div>
@if($result['incomplete']->isNotEmpty())<div class="alert alert-warning">{{ __('Incomplete: one or more authorized School reports could not be read. Totals below exclude them.') }}</div>@endif
<div class="row"><div class="col-md-3"><div class="card"><div class="card-body">{{ __('Operating Income') }}<h4>{{ number_format($result['summary']['operating_income'],2) }}</h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body">{{ __('Operating Expense') }}<h4>{{ number_format($result['summary']['operating_expense'],2) }}</h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body">{{ __('Operating Net') }}<h4>{{ number_format($result['summary']['operating_net'],2) }}</h4></div></div></div><div class="col-md-3"><div class="card"><div class="card-body">{{ __('Internal Transfer') }}<h4>{{ number_format($result['summary']['internal_transfer_amount'],2) }}</h4></div></div></div></div>
<a class="btn btn-outline-primary mb-3" href="{{ route('finance-groups.reports.export', [$financeGroup, request()->query()]) }}">{{ __('Export CSV') }}</a>
<div class="card"><div class="card-body table-responsive"><table class="table"><thead><tr><th>{{ __('Date') }}</th><th>{{ __('School') }}</th><th>{{ __('Type') }}</th><th>{{ __('Reference') }}</th><th>{{ __('Fund Account') }}</th><th>{{ __('Money In') }}</th><th>{{ __('Money Out') }}</th></tr></thead><tbody>@forelse($result['rows'] as $row)<tr><td>{{ $row['posting_date'] }}</td><td>{{ $row['school_name'] }}</td><td>{{ $row['transaction_class'] }}</td><td>{{ $row['reference_no'] }}</td><td>{{ $row['fund_account_name'] }}</td><td>{{ number_format($row['money_in'],2) }}</td><td>{{ number_format($row['money_out'],2) }}</td></tr>@empty<tr><td colspan="7">{{ __('No authorized Ledger records found.') }}</td></tr>@endforelse</tbody></table></div></div>
</div>@endsection
